### ISSUE TITLE
Error to configure project locally

### ISSUE THREAD

**Issue by gilsondev** [cuducos/my-internet-speed#14] opened 2018-12-23 20:32 UTC
I'm follow the `README.md` to test locally the project, but when run the dashboard fired this error:

![image](https://user-images.githubusercontent.com/265653/50387355-161e3f00-06e1-11e9-9638-f5a774045732.png)

**Comment by cuducos** [comment] 2018-12-23 22:16
Duplicate of #10

**Closed by cuducos** 2018-12-23 22:16 UTC
